package commanddocs

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"dzcli/cli"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

const (
	defaultOutputDir = "docs"
	documentName     = "commands.md"
)

var (
	mkdirAll    = os.MkdirAll
	writeFile   = os.WriteFile
	rootCommand = func() *cobra.Command {
		return cli.NewRootCommand(io.Discard, io.Discard)
	}
)

func Main(args []string, stdout io.Writer, stderr io.Writer) int {
	if err := Run(args, stdout); err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}

func Run(args []string, stdout io.Writer) error {
	outputDir, err := parseArgs(args)
	if err != nil {
		return err
	}
	path, err := Generate(outputDir)
	if err != nil {
		return err
	}
	fmt.Fprintf(stdout, "generated %s\n", path)
	return nil
}

func Generate(outputDir string) (string, error) {
	command := rootCommand()
	content := Render(command)

	if err := mkdirAll(outputDir, 0o755); err != nil {
		return "", err
	}

	path := filepath.Join(outputDir, documentName)
	if err := writeFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func Render(command *cobra.Command) string {
	var builder strings.Builder
	builder.WriteString("# dzcli Command Reference\n\n")
	builder.WriteString("> Generated by `go run ./cmd/gendocs`; do not edit by hand.\n\n")
	for _, child := range commandTree(command) {
		renderCommand(&builder, child)
	}
	return builder.String()
}

func parseArgs(args []string) (string, error) {
	switch len(args) {
	case 0:
		return defaultOutputDir, nil
	case 2:
		if args[0] != "--output" {
			return "", usageError()
		}
		if strings.TrimSpace(args[1]) == "" {
			return "", fmt.Errorf("--output requires a directory")
		}
		return args[1], nil
	default:
		return "", usageError()
	}
}

func usageError() error {
	return fmt.Errorf("usage: go run ./cmd/gendocs [--output docs]")
}

func commandTree(command *cobra.Command) []*cobra.Command {
	commands := []*cobra.Command{command}
	for _, child := range visibleCommands(command) {
		commands = append(commands, commandTree(child)...)
	}
	return commands
}

func renderCommand(builder *strings.Builder, command *cobra.Command) {
	builder.WriteString("## ")
	builder.WriteString(command.CommandPath())
	builder.WriteString("\n\n")

	if command.Short != "" {
		builder.WriteString(command.Short)
		builder.WriteString("\n\n")
	}
	if command.Long != "" {
		builder.WriteString(strings.TrimSpace(command.Long))
		builder.WriteString("\n\n")
	}

	builder.WriteString("### Usage\n\n")
	builder.WriteString("```text\n")
	builder.WriteString(command.UseLine())
	builder.WriteString("\n```\n\n")

	if command.Example != "" {
		builder.WriteString("### Examples\n\n")
		builder.WriteString("```text\n")
		builder.WriteString(strings.TrimSpace(command.Example))
		builder.WriteString("\n```\n\n")
	}

	renderSubcommands(builder, command)
	renderFlags(builder, "Flags", command.NonInheritedFlags())
	renderFlags(builder, "Inherited Flags", command.InheritedFlags())
}

func renderSubcommands(builder *strings.Builder, command *cobra.Command) {
	commands := visibleCommands(command)
	if len(commands) == 0 {
		return
	}

	builder.WriteString("### Commands\n\n")
	builder.WriteString("| Command | Description |\n")
	builder.WriteString("| --- | --- |\n")
	for _, child := range commands {
		builder.WriteString("| `")
		builder.WriteString(child.Name())
		builder.WriteString("` | ")
		builder.WriteString(escapeMarkdownTable(child.Short))
		builder.WriteString(" |\n")
	}
	builder.WriteString("\n")
}

func renderFlags(builder *strings.Builder, title string, flags *pflag.FlagSet) {
	rows := flagRows(flags)
	if len(rows) == 0 {
		return
	}

	builder.WriteString("### ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	builder.WriteString("| Flag | Default | Description |\n")
	builder.WriteString("| --- | --- | --- |\n")
	for _, row := range rows {
		builder.WriteString("| `")
		builder.WriteString(row.name)
		builder.WriteString("` | `")
		builder.WriteString(row.defaultValue)
		builder.WriteString("` | ")
		builder.WriteString(escapeMarkdownTable(row.usage))
		builder.WriteString(" |\n")
	}
	builder.WriteString("\n")
}

type flagRow struct {
	name         string
	defaultValue string
	usage        string
}

func flagRows(flags *pflag.FlagSet) []flagRow {
	var rows []flagRow
	flags.VisitAll(func(flag *pflag.Flag) {
		if flag.Hidden {
			return
		}
		rows = append(rows, flagRow{
			name:         flagName(flag),
			defaultValue: flag.DefValue,
			usage:        flag.Usage,
		})
	})
	sort.Slice(rows, func(left int, right int) bool {
		return rows[left].name < rows[right].name
	})
	return rows
}

func flagName(flag *pflag.Flag) string {
	if flag.Shorthand == "" {
		return "--" + flag.Name
	}
	return "-" + flag.Shorthand + ", --" + flag.Name
}

func visibleCommands(command *cobra.Command) []*cobra.Command {
	var commands []*cobra.Command
	for _, child := range command.Commands() {
		if child.Hidden {
			continue
		}
		commands = append(commands, child)
	}
	sort.Slice(commands, func(left int, right int) bool {
		return commands[left].Name() < commands[right].Name()
	})
	return commands
}

func escapeMarkdownTable(value string) string {
	value = strings.ReplaceAll(value, "\n", "<br>")
	return strings.ReplaceAll(value, "|", "\\|")
}
